In [2]:
import numpy as np
from sklearn import datasets

In [3]:
iris = datasets.load_iris()

In [5]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [6]:
x = iris.data
y = iris.target

In [7]:
x.shape, y.shape

((150, 4), (150,))

In [8]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,train_size=2/3,stratify=y)

/usr/lib/python3/dist-packages/sklearn/model_selection/_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)


In [9]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((100, 4), (50, 4), (100,), (50,))

In [10]:
from sklearn.tree import DecisionTreeClassifier, export_graphviz
arbol = DecisionTreeClassifier(criterion='entropy')

In [15]:
arbol.fit(x_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [16]:
y_test_predict = arbol.predict(x_test)

In [17]:
y_test_predict == y_test

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])

In [18]:
np.sum(y_test_predict == y_test)/y_test.shape[0]

0.98

In [24]:
from sklearn.metrics import confusion_matrix
cnf_matrix = confusion_matrix(y_test,y_test_predict)
print(cnf_matrix)

[[17  0  0]
 [ 0 16  0]
 [ 0  1 16]]


In [26]:
dot_data = export_graphviz(arbol, feature_names=iris.feature_names, out_file="arbol.dot")

In [27]:
export_graphviz?